formatter = "nixfmt"
top-level-blank-lines = 1

[args]
first = ["lib", "config", "pkgs", "inputs", "inputs'", "self", "self'"]
last = ["<defaulted>", "..."]

[lets]
sort = true

[attrs]
first = ["flake-file", "imports", "perSystem"]
flatten = true
merge = true


[[overrides]]
path = "**.flake-file.inputs.*"
attrs.first = ["url", "inputs", "flake"]

[[files]]
pattern = "**/*.pkg.nix"
preset = "nixpkgs-package"
