catalogMode: strict

save-prefix: ""

save-workspace-protocol: rolling

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - vite@6.4.1
packages:
  - docs
catalog:
  "@antfu/eslint-config": ^7.0.1
  "@astrojs/starlight": 0.37.3
  "@catppuccin/starlight": ^1.0.2
  astro: 5.16.11
  astro-eslint-parser: ^1.2.2
  dprint-plugin-malva: ^0.15.2
  dprint-plugin-markup: ^0.25.3
  eslint: ^9.39.2
  eslint-plugin-astro: ^1.5.0
  eslint-plugin-format: ^1.3.1
  sharp: 0.34.2
  typescript: ^5.9.3
  typescript-language-server: ^5.1.3
